// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number
// @generated from protobuf file "exposed-donation.proto" (syntax proto3)
// tslint:disable
import { CommonResponse } from "./exposed-common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Pagination } from "./exposed-common";
import { DonationStatus } from "./exposed-common";
import { DonationType } from "./exposed-common";
/**
 * @generated from protobuf message UserDonationRequest
 */
export interface UserDonationRequest {
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * @generated from protobuf field: string description = 2
     */
    description: string;
    /**
     * @generated from protobuf field: DonationType type = 3
     */
    type: DonationType;
    /**
     * @generated from protobuf field: string product_url = 4
     */
    productUrl: string;
}
/**
 * @generated from protobuf message GetDonationRequest
 */
export interface GetDonationRequest {
    /**
     * @generated from protobuf field: int32 page = 1
     */
    page: number;
    /**
     * @generated from protobuf field: int32 limit = 2
     */
    limit: number;
    /**
     * @generated from protobuf field: string search = 3
     */
    search: string;
    /**
     * @generated from protobuf field: DonationType type = 4
     */
    type: DonationType;
    /**
     * @generated from protobuf field: DonationStatus status = 5
     */
    status: DonationStatus;
}
/**
 * @generated from protobuf message DonationItems
 */
export interface DonationItems {
    /**
     * @generated from protobuf field: string id = 6
     */
    id: string;
    /**
     * @generated from protobuf field: string createdAt = 7
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updatedAt = 8
     */
    updatedAt: string;
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * @generated from protobuf field: string description = 2
     */
    description: string;
    /**
     * @generated from protobuf field: string url = 3
     */
    url: string;
    /**
     * @generated from protobuf field: DonationType type = 4
     */
    type: DonationType;
    /**
     * @generated from protobuf field: DonationStatus status = 5
     */
    status: DonationStatus;
}
/**
 * @generated from protobuf message PageDonation
 */
export interface PageDonation {
    /**
     * @generated from protobuf field: repeated DonationItems data = 1
     */
    data: DonationItems[];
    /**
     * @generated from protobuf field: Pagination pagination = 2
     */
    pagination?: Pagination;
}
/**
 * @generated from protobuf message GetDonationResponse
 */
export interface GetDonationResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: PageDonation data = 3
     */
    data?: PageDonation;
}
/**
 * @generated from protobuf message ClaimDonationRequest
 */
export interface ClaimDonationRequest {
    /**
     * @generated from protobuf field: string donationId = 1
     */
    donationId: string;
}
/**
 * @generated from protobuf message GotDonationRequest
 */
export interface GotDonationRequest {
    /**
     * @generated from protobuf field: string donationId = 1
     */
    donationId: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class UserDonationRequest$Type extends MessageType<UserDonationRequest> {
    constructor() {
        super("UserDonationRequest", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["DonationType", DonationType] },
            { no: 4, name: "product_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UserDonationRequest>): UserDonationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.description = "";
        message.type = 0;
        message.productUrl = "";
        if (value !== undefined)
            reflectionMergePartial<UserDonationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserDonationRequest): UserDonationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string description */ 2:
                    message.description = reader.string();
                    break;
                case /* DonationType type */ 3:
                    message.type = reader.int32();
                    break;
                case /* string product_url */ 4:
                    message.productUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserDonationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string description = 2; */
        if (message.description !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.description);
        /* DonationType type = 3; */
        if (message.type !== 0)
            writer.tag(3, WireType.Varint).int32(message.type);
        /* string product_url = 4; */
        if (message.productUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.productUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UserDonationRequest
 */
export const UserDonationRequest = new UserDonationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetDonationRequest$Type extends MessageType<GetDonationRequest> {
    constructor() {
        super("GetDonationRequest", [
            { no: 1, name: "page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "search", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "type", kind: "enum", T: () => ["DonationType", DonationType] },
            { no: 5, name: "status", kind: "enum", T: () => ["DonationStatus", DonationStatus] }
        ]);
    }
    create(value?: PartialMessage<GetDonationRequest>): GetDonationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.page = 0;
        message.limit = 0;
        message.search = "";
        message.type = 0;
        message.status = 0;
        if (value !== undefined)
            reflectionMergePartial<GetDonationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDonationRequest): GetDonationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 page */ 1:
                    message.page = reader.int32();
                    break;
                case /* int32 limit */ 2:
                    message.limit = reader.int32();
                    break;
                case /* string search */ 3:
                    message.search = reader.string();
                    break;
                case /* DonationType type */ 4:
                    message.type = reader.int32();
                    break;
                case /* DonationStatus status */ 5:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDonationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 page = 1; */
        if (message.page !== 0)
            writer.tag(1, WireType.Varint).int32(message.page);
        /* int32 limit = 2; */
        if (message.limit !== 0)
            writer.tag(2, WireType.Varint).int32(message.limit);
        /* string search = 3; */
        if (message.search !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.search);
        /* DonationType type = 4; */
        if (message.type !== 0)
            writer.tag(4, WireType.Varint).int32(message.type);
        /* DonationStatus status = 5; */
        if (message.status !== 0)
            writer.tag(5, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message GetDonationRequest
 */
export const GetDonationRequest = new GetDonationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DonationItems$Type extends MessageType<DonationItems> {
    constructor() {
        super("DonationItems", [
            { no: 6, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "createdAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "updatedAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "type", kind: "enum", T: () => ["DonationType", DonationType] },
            { no: 5, name: "status", kind: "enum", T: () => ["DonationStatus", DonationStatus] }
        ]);
    }
    create(value?: PartialMessage<DonationItems>): DonationItems {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.createdAt = "";
        message.updatedAt = "";
        message.title = "";
        message.description = "";
        message.url = "";
        message.type = 0;
        message.status = 0;
        if (value !== undefined)
            reflectionMergePartial<DonationItems>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DonationItems): DonationItems {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 6:
                    message.id = reader.string();
                    break;
                case /* string createdAt */ 7:
                    message.createdAt = reader.string();
                    break;
                case /* string updatedAt */ 8:
                    message.updatedAt = reader.string();
                    break;
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string description */ 2:
                    message.description = reader.string();
                    break;
                case /* string url */ 3:
                    message.url = reader.string();
                    break;
                case /* DonationType type */ 4:
                    message.type = reader.int32();
                    break;
                case /* DonationStatus status */ 5:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DonationItems, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string description = 2; */
        if (message.description !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.description);
        /* string url = 3; */
        if (message.url !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.url);
        /* DonationType type = 4; */
        if (message.type !== 0)
            writer.tag(4, WireType.Varint).int32(message.type);
        /* DonationStatus status = 5; */
        if (message.status !== 0)
            writer.tag(5, WireType.Varint).int32(message.status);
        /* string id = 6; */
        if (message.id !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.id);
        /* string createdAt = 7; */
        if (message.createdAt !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.createdAt);
        /* string updatedAt = 8; */
        if (message.updatedAt !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.updatedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message DonationItems
 */
export const DonationItems = new DonationItems$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageDonation$Type extends MessageType<PageDonation> {
    constructor() {
        super("PageDonation", [
            { no: 1, name: "data", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => DonationItems },
            { no: 2, name: "pagination", kind: "message", T: () => Pagination }
        ]);
    }
    create(value?: PartialMessage<PageDonation>): PageDonation {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = [];
        if (value !== undefined)
            reflectionMergePartial<PageDonation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageDonation): PageDonation {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated DonationItems data */ 1:
                    message.data.push(DonationItems.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* Pagination pagination */ 2:
                    message.pagination = Pagination.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageDonation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated DonationItems data = 1; */
        for (let i = 0; i < message.data.length; i++)
            DonationItems.internalBinaryWrite(message.data[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* Pagination pagination = 2; */
        if (message.pagination)
            Pagination.internalBinaryWrite(message.pagination, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PageDonation
 */
export const PageDonation = new PageDonation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetDonationResponse$Type extends MessageType<GetDonationResponse> {
    constructor() {
        super("GetDonationResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", T: () => PageDonation }
        ]);
    }
    create(value?: PartialMessage<GetDonationResponse>): GetDonationResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<GetDonationResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDonationResponse): GetDonationResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* PageDonation data */ 3:
                    message.data = PageDonation.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDonationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* PageDonation data = 3; */
        if (message.data)
            PageDonation.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message GetDonationResponse
 */
export const GetDonationResponse = new GetDonationResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClaimDonationRequest$Type extends MessageType<ClaimDonationRequest> {
    constructor() {
        super("ClaimDonationRequest", [
            { no: 1, name: "donationId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ClaimDonationRequest>): ClaimDonationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.donationId = "";
        if (value !== undefined)
            reflectionMergePartial<ClaimDonationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ClaimDonationRequest): ClaimDonationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string donationId */ 1:
                    message.donationId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ClaimDonationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string donationId = 1; */
        if (message.donationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.donationId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ClaimDonationRequest
 */
export const ClaimDonationRequest = new ClaimDonationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GotDonationRequest$Type extends MessageType<GotDonationRequest> {
    constructor() {
        super("GotDonationRequest", [
            { no: 1, name: "donationId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GotDonationRequest>): GotDonationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.donationId = "";
        if (value !== undefined)
            reflectionMergePartial<GotDonationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GotDonationRequest): GotDonationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string donationId */ 1:
                    message.donationId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GotDonationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string donationId = 1; */
        if (message.donationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.donationId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message GotDonationRequest
 */
export const GotDonationRequest = new GotDonationRequest$Type();
/**
 * @generated ServiceType for protobuf service DonationService
 */
export const DonationService = new ServiceType("DonationService", [
    { name: "Donate", options: {}, I: UserDonationRequest, O: CommonResponse },
    { name: "GetMyDonations", options: {}, I: GetDonationRequest, O: GetDonationResponse },
    { name: "GetDonations", options: {}, I: GetDonationRequest, O: GetDonationResponse },
    { name: "ClaimDonation", options: {}, I: ClaimDonationRequest, O: CommonResponse },
    { name: "GotDonation", options: {}, I: GotDonationRequest, O: CommonResponse }
]);
