// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number
// @generated from protobuf file "exposed-auth.proto" (syntax proto3)
// tslint:disable
import { EmptyRequest } from "./exposed-common";
import { CommonResponse } from "./exposed-common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { User } from "./exposed-common";
import { Organization } from "./exposed-common";
import { Role } from "./exposed-common";
import { AuthStatus } from "./exposed-common";
/**
 * @generated from protobuf message RegisterAdminRequest
 */
export interface RegisterAdminRequest {
    /**
     * @generated from protobuf field: string email = 1
     */
    email: string;
    /**
     * @generated from protobuf field: string password = 2
     */
    password: string;
    /**
     * @generated from protobuf field: string phone_number = 3
     */
    phoneNumber: string;
    /**
     * @generated from protobuf field: string firstName = 4
     */
    firstName: string;
    /**
     * @generated from protobuf field: string middleName = 5
     */
    middleName: string;
    /**
     * @generated from protobuf field: string lastName = 6
     */
    lastName: string;
}
/**
 * @generated from protobuf message LoginRequest
 */
export interface LoginRequest {
    /**
     * @generated from protobuf field: string username = 1
     */
    username: string;
    /**
     * @generated from protobuf field: string password = 2
     */
    password: string;
}
/**
 * @generated from protobuf message AuthTokenResponse
 */
export interface AuthTokenResponse {
    /**
     * @generated from protobuf field: string accessToken = 1
     */
    accessToken: string;
    /**
     * @generated from protobuf field: string refreshToken = 2
     */
    refreshToken: string;
}
/**
 * @generated from protobuf message LoginResponse
 */
export interface LoginResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: AuthTokenResponse data = 3
     */
    data?: AuthTokenResponse;
}
/**
 * @generated from protobuf message RefreshTokenRequest
 */
export interface RefreshTokenRequest {
    /**
     * @generated from protobuf field: string refreshToken = 1
     */
    refreshToken: string;
}
/**
 * @generated from protobuf message RefreshTokenResponse
 */
export interface RefreshTokenResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: AuthTokenResponse data = 3
     */
    data?: AuthTokenResponse;
}
/**
 * @generated from protobuf message RegisterUserRequest
 */
export interface RegisterUserRequest {
    /**
     * @generated from protobuf field: string email = 1
     */
    email: string;
    /**
     * @generated from protobuf field: string password = 2
     */
    password: string;
    /**
     * @generated from protobuf field: string phone_number = 3
     */
    phoneNumber: string;
    /**
     * @generated from protobuf field: string firstName = 4
     */
    firstName: string;
    /**
     * @generated from protobuf field: string middleName = 5
     */
    middleName: string;
    /**
     * @generated from protobuf field: string lastName = 6
     */
    lastName: string;
    /**
     * @generated from protobuf field: float latitude = 7
     */
    latitude: number;
    /**
     * @generated from protobuf field: float longitude = 8
     */
    longitude: number;
}
/**
 * @generated from protobuf message RegisterOrganizationRequest
 */
export interface RegisterOrganizationRequest {
    /**
     * @generated from protobuf field: string email = 4
     */
    email: string;
    /**
     * @generated from protobuf field: string password = 3
     */
    password: string;
    /**
     * @generated from protobuf field: string phone_number = 2
     */
    phoneNumber: string;
    /**
     * @generated from protobuf field: string organization_name = 1
     */
    organizationName: string;
    /**
     * @generated from protobuf field: string organizationHeadFirstName = 10
     */
    organizationHeadFirstName: string;
    /**
     * @generated from protobuf field: string organizationHeadMiddleName = 11
     */
    organizationHeadMiddleName: string;
    /**
     * @generated from protobuf field: string organizationHeadLastName = 12
     */
    organizationHeadLastName: string;
    /**
     * @generated from protobuf field: string organizationHeadPhoneNumber = 13
     */
    organizationHeadPhoneNumber: string;
    /**
     * @generated from protobuf field: string address = 5
     */
    address: string;
    /**
     * @generated from protobuf field: float latitude = 6
     */
    latitude: number;
    /**
     * @generated from protobuf field: float longitude = 7
     */
    longitude: number;
    /**
     * @generated from protobuf field: string govt_id = 8
     */
    govtId: string;
    /**
     * @generated from protobuf field: string contact_number = 9
     */
    contactNumber: string;
}
/**
 * @generated from protobuf message LogoutRequest
 */
export interface LogoutRequest {
}
/**
 * @generated from protobuf message UpdateAuthStatusRequest
 */
export interface UpdateAuthStatusRequest {
    /**
     * @generated from protobuf field: string auth_id = 1
     */
    authId: string;
    /**
     * @generated from protobuf field: AuthStatus status = 2
     */
    status: AuthStatus;
}
/**
 * @generated from protobuf message MyInfoData
 */
export interface MyInfoData {
    /**
     * @generated from protobuf field: string email = 1
     */
    email: string;
    /**
     * @generated from protobuf field: string phone = 2
     */
    phone: string;
    /**
     * @generated from protobuf field: Role role = 3
     */
    role: Role;
    /**
     * @generated from protobuf field: AuthStatus status = 4
     */
    status: AuthStatus;
    /**
     * @generated from protobuf field: Organization organization = 5
     */
    organization?: Organization;
    /**
     * @generated from protobuf field: User user = 6
     */
    user?: User;
}
/**
 * @generated from protobuf message MyInfoResponse
 */
export interface MyInfoResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: MyInfoData data = 3
     */
    data?: MyInfoData;
}
// @generated message type with reflection information, may provide speed optimized methods
class RegisterAdminRequest$Type extends MessageType<RegisterAdminRequest> {
    constructor() {
        super("RegisterAdminRequest", [
            { no: 1, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "phone_number", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "firstName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "middleName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "lastName", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterAdminRequest>): RegisterAdminRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.email = "";
        message.password = "";
        message.phoneNumber = "";
        message.firstName = "";
        message.middleName = "";
        message.lastName = "";
        if (value !== undefined)
            reflectionMergePartial<RegisterAdminRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterAdminRequest): RegisterAdminRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string email */ 1:
                    message.email = reader.string();
                    break;
                case /* string password */ 2:
                    message.password = reader.string();
                    break;
                case /* string phone_number */ 3:
                    message.phoneNumber = reader.string();
                    break;
                case /* string firstName */ 4:
                    message.firstName = reader.string();
                    break;
                case /* string middleName */ 5:
                    message.middleName = reader.string();
                    break;
                case /* string lastName */ 6:
                    message.lastName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterAdminRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string email = 1; */
        if (message.email !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.email);
        /* string password = 2; */
        if (message.password !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.password);
        /* string phone_number = 3; */
        if (message.phoneNumber !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.phoneNumber);
        /* string firstName = 4; */
        if (message.firstName !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.firstName);
        /* string middleName = 5; */
        if (message.middleName !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.middleName);
        /* string lastName = 6; */
        if (message.lastName !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.lastName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message RegisterAdminRequest
 */
export const RegisterAdminRequest = new RegisterAdminRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LoginRequest$Type extends MessageType<LoginRequest> {
    constructor() {
        super("LoginRequest", [
            { no: 1, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LoginRequest>): LoginRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.username = "";
        message.password = "";
        if (value !== undefined)
            reflectionMergePartial<LoginRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LoginRequest): LoginRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string username */ 1:
                    message.username = reader.string();
                    break;
                case /* string password */ 2:
                    message.password = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LoginRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string username = 1; */
        if (message.username !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.username);
        /* string password = 2; */
        if (message.password !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.password);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message LoginRequest
 */
export const LoginRequest = new LoginRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AuthTokenResponse$Type extends MessageType<AuthTokenResponse> {
    constructor() {
        super("AuthTokenResponse", [
            { no: 1, name: "accessToken", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "refreshToken", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AuthTokenResponse>): AuthTokenResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accessToken = "";
        message.refreshToken = "";
        if (value !== undefined)
            reflectionMergePartial<AuthTokenResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AuthTokenResponse): AuthTokenResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string accessToken */ 1:
                    message.accessToken = reader.string();
                    break;
                case /* string refreshToken */ 2:
                    message.refreshToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AuthTokenResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string accessToken = 1; */
        if (message.accessToken !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.accessToken);
        /* string refreshToken = 2; */
        if (message.refreshToken !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.refreshToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message AuthTokenResponse
 */
export const AuthTokenResponse = new AuthTokenResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LoginResponse$Type extends MessageType<LoginResponse> {
    constructor() {
        super("LoginResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", T: () => AuthTokenResponse }
        ]);
    }
    create(value?: PartialMessage<LoginResponse>): LoginResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<LoginResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LoginResponse): LoginResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* AuthTokenResponse data */ 3:
                    message.data = AuthTokenResponse.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LoginResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* AuthTokenResponse data = 3; */
        if (message.data)
            AuthTokenResponse.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message LoginResponse
 */
export const LoginResponse = new LoginResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RefreshTokenRequest$Type extends MessageType<RefreshTokenRequest> {
    constructor() {
        super("RefreshTokenRequest", [
            { no: 1, name: "refreshToken", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RefreshTokenRequest>): RefreshTokenRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.refreshToken = "";
        if (value !== undefined)
            reflectionMergePartial<RefreshTokenRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RefreshTokenRequest): RefreshTokenRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string refreshToken */ 1:
                    message.refreshToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RefreshTokenRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string refreshToken = 1; */
        if (message.refreshToken !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.refreshToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message RefreshTokenRequest
 */
export const RefreshTokenRequest = new RefreshTokenRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RefreshTokenResponse$Type extends MessageType<RefreshTokenResponse> {
    constructor() {
        super("RefreshTokenResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", T: () => AuthTokenResponse }
        ]);
    }
    create(value?: PartialMessage<RefreshTokenResponse>): RefreshTokenResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<RefreshTokenResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RefreshTokenResponse): RefreshTokenResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* AuthTokenResponse data */ 3:
                    message.data = AuthTokenResponse.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RefreshTokenResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* AuthTokenResponse data = 3; */
        if (message.data)
            AuthTokenResponse.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message RefreshTokenResponse
 */
export const RefreshTokenResponse = new RefreshTokenResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterUserRequest$Type extends MessageType<RegisterUserRequest> {
    constructor() {
        super("RegisterUserRequest", [
            { no: 1, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "phone_number", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "firstName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "middleName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "lastName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "latitude", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 8, name: "longitude", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterUserRequest>): RegisterUserRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.email = "";
        message.password = "";
        message.phoneNumber = "";
        message.firstName = "";
        message.middleName = "";
        message.lastName = "";
        message.latitude = 0;
        message.longitude = 0;
        if (value !== undefined)
            reflectionMergePartial<RegisterUserRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterUserRequest): RegisterUserRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string email */ 1:
                    message.email = reader.string();
                    break;
                case /* string password */ 2:
                    message.password = reader.string();
                    break;
                case /* string phone_number */ 3:
                    message.phoneNumber = reader.string();
                    break;
                case /* string firstName */ 4:
                    message.firstName = reader.string();
                    break;
                case /* string middleName */ 5:
                    message.middleName = reader.string();
                    break;
                case /* string lastName */ 6:
                    message.lastName = reader.string();
                    break;
                case /* float latitude */ 7:
                    message.latitude = reader.float();
                    break;
                case /* float longitude */ 8:
                    message.longitude = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterUserRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string email = 1; */
        if (message.email !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.email);
        /* string password = 2; */
        if (message.password !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.password);
        /* string phone_number = 3; */
        if (message.phoneNumber !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.phoneNumber);
        /* string firstName = 4; */
        if (message.firstName !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.firstName);
        /* string middleName = 5; */
        if (message.middleName !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.middleName);
        /* string lastName = 6; */
        if (message.lastName !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.lastName);
        /* float latitude = 7; */
        if (message.latitude !== 0)
            writer.tag(7, WireType.Bit32).float(message.latitude);
        /* float longitude = 8; */
        if (message.longitude !== 0)
            writer.tag(8, WireType.Bit32).float(message.longitude);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message RegisterUserRequest
 */
export const RegisterUserRequest = new RegisterUserRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterOrganizationRequest$Type extends MessageType<RegisterOrganizationRequest> {
    constructor() {
        super("RegisterOrganizationRequest", [
            { no: 4, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "phone_number", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 1, name: "organization_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "organizationHeadFirstName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "organizationHeadMiddleName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "organizationHeadLastName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "organizationHeadPhoneNumber", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "latitude", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 7, name: "longitude", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 8, name: "govt_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "contact_number", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterOrganizationRequest>): RegisterOrganizationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.email = "";
        message.password = "";
        message.phoneNumber = "";
        message.organizationName = "";
        message.organizationHeadFirstName = "";
        message.organizationHeadMiddleName = "";
        message.organizationHeadLastName = "";
        message.organizationHeadPhoneNumber = "";
        message.address = "";
        message.latitude = 0;
        message.longitude = 0;
        message.govtId = "";
        message.contactNumber = "";
        if (value !== undefined)
            reflectionMergePartial<RegisterOrganizationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterOrganizationRequest): RegisterOrganizationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string email */ 4:
                    message.email = reader.string();
                    break;
                case /* string password */ 3:
                    message.password = reader.string();
                    break;
                case /* string phone_number */ 2:
                    message.phoneNumber = reader.string();
                    break;
                case /* string organization_name */ 1:
                    message.organizationName = reader.string();
                    break;
                case /* string organizationHeadFirstName */ 10:
                    message.organizationHeadFirstName = reader.string();
                    break;
                case /* string organizationHeadMiddleName */ 11:
                    message.organizationHeadMiddleName = reader.string();
                    break;
                case /* string organizationHeadLastName */ 12:
                    message.organizationHeadLastName = reader.string();
                    break;
                case /* string organizationHeadPhoneNumber */ 13:
                    message.organizationHeadPhoneNumber = reader.string();
                    break;
                case /* string address */ 5:
                    message.address = reader.string();
                    break;
                case /* float latitude */ 6:
                    message.latitude = reader.float();
                    break;
                case /* float longitude */ 7:
                    message.longitude = reader.float();
                    break;
                case /* string govt_id */ 8:
                    message.govtId = reader.string();
                    break;
                case /* string contact_number */ 9:
                    message.contactNumber = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterOrganizationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string organization_name = 1; */
        if (message.organizationName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.organizationName);
        /* string phone_number = 2; */
        if (message.phoneNumber !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.phoneNumber);
        /* string password = 3; */
        if (message.password !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.password);
        /* string email = 4; */
        if (message.email !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.email);
        /* string address = 5; */
        if (message.address !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.address);
        /* float latitude = 6; */
        if (message.latitude !== 0)
            writer.tag(6, WireType.Bit32).float(message.latitude);
        /* float longitude = 7; */
        if (message.longitude !== 0)
            writer.tag(7, WireType.Bit32).float(message.longitude);
        /* string govt_id = 8; */
        if (message.govtId !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.govtId);
        /* string contact_number = 9; */
        if (message.contactNumber !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.contactNumber);
        /* string organizationHeadFirstName = 10; */
        if (message.organizationHeadFirstName !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.organizationHeadFirstName);
        /* string organizationHeadMiddleName = 11; */
        if (message.organizationHeadMiddleName !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.organizationHeadMiddleName);
        /* string organizationHeadLastName = 12; */
        if (message.organizationHeadLastName !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.organizationHeadLastName);
        /* string organizationHeadPhoneNumber = 13; */
        if (message.organizationHeadPhoneNumber !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.organizationHeadPhoneNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message RegisterOrganizationRequest
 */
export const RegisterOrganizationRequest = new RegisterOrganizationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LogoutRequest$Type extends MessageType<LogoutRequest> {
    constructor() {
        super("LogoutRequest", []);
    }
    create(value?: PartialMessage<LogoutRequest>): LogoutRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<LogoutRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LogoutRequest): LogoutRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LogoutRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message LogoutRequest
 */
export const LogoutRequest = new LogoutRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateAuthStatusRequest$Type extends MessageType<UpdateAuthStatusRequest> {
    constructor() {
        super("UpdateAuthStatusRequest", [
            { no: 1, name: "auth_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "status", kind: "enum", T: () => ["AuthStatus", AuthStatus] }
        ]);
    }
    create(value?: PartialMessage<UpdateAuthStatusRequest>): UpdateAuthStatusRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.authId = "";
        message.status = 0;
        if (value !== undefined)
            reflectionMergePartial<UpdateAuthStatusRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateAuthStatusRequest): UpdateAuthStatusRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string auth_id */ 1:
                    message.authId = reader.string();
                    break;
                case /* AuthStatus status */ 2:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateAuthStatusRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string auth_id = 1; */
        if (message.authId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.authId);
        /* AuthStatus status = 2; */
        if (message.status !== 0)
            writer.tag(2, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UpdateAuthStatusRequest
 */
export const UpdateAuthStatusRequest = new UpdateAuthStatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MyInfoData$Type extends MessageType<MyInfoData> {
    constructor() {
        super("MyInfoData", [
            { no: 1, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "role", kind: "enum", T: () => ["Role", Role] },
            { no: 4, name: "status", kind: "enum", T: () => ["AuthStatus", AuthStatus] },
            { no: 5, name: "organization", kind: "message", T: () => Organization },
            { no: 6, name: "user", kind: "message", T: () => User }
        ]);
    }
    create(value?: PartialMessage<MyInfoData>): MyInfoData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.email = "";
        message.phone = "";
        message.role = 0;
        message.status = 0;
        if (value !== undefined)
            reflectionMergePartial<MyInfoData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MyInfoData): MyInfoData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string email */ 1:
                    message.email = reader.string();
                    break;
                case /* string phone */ 2:
                    message.phone = reader.string();
                    break;
                case /* Role role */ 3:
                    message.role = reader.int32();
                    break;
                case /* AuthStatus status */ 4:
                    message.status = reader.int32();
                    break;
                case /* Organization organization */ 5:
                    message.organization = Organization.internalBinaryRead(reader, reader.uint32(), options, message.organization);
                    break;
                case /* User user */ 6:
                    message.user = User.internalBinaryRead(reader, reader.uint32(), options, message.user);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MyInfoData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string email = 1; */
        if (message.email !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.email);
        /* string phone = 2; */
        if (message.phone !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.phone);
        /* Role role = 3; */
        if (message.role !== 0)
            writer.tag(3, WireType.Varint).int32(message.role);
        /* AuthStatus status = 4; */
        if (message.status !== 0)
            writer.tag(4, WireType.Varint).int32(message.status);
        /* Organization organization = 5; */
        if (message.organization)
            Organization.internalBinaryWrite(message.organization, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* User user = 6; */
        if (message.user)
            User.internalBinaryWrite(message.user, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message MyInfoData
 */
export const MyInfoData = new MyInfoData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MyInfoResponse$Type extends MessageType<MyInfoResponse> {
    constructor() {
        super("MyInfoResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "message", T: () => MyInfoData }
        ]);
    }
    create(value?: PartialMessage<MyInfoResponse>): MyInfoResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<MyInfoResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MyInfoResponse): MyInfoResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* MyInfoData data */ 3:
                    message.data = MyInfoData.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MyInfoResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* MyInfoData data = 3; */
        if (message.data)
            MyInfoData.internalBinaryWrite(message.data, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message MyInfoResponse
 */
export const MyInfoResponse = new MyInfoResponse$Type();
/**
 * @generated ServiceType for protobuf service AuthService
 */
export const AuthService = new ServiceType("AuthService", [
    { name: "Login", options: {}, I: LoginRequest, O: LoginResponse },
    { name: "RefreshToken", options: {}, I: RefreshTokenRequest, O: RefreshTokenResponse },
    { name: "RegisterUser", options: {}, I: RegisterUserRequest, O: CommonResponse },
    { name: "RegisterOrganization", options: {}, I: RegisterOrganizationRequest, O: CommonResponse },
    { name: "RegisterAdmin", options: {}, I: RegisterAdminRequest, O: CommonResponse },
    { name: "UpdateAuthStatus", options: {}, I: UpdateAuthStatusRequest, O: CommonResponse },
    { name: "MyInfo", options: {}, I: EmptyRequest, O: MyInfoResponse },
    { name: "Logout", options: {}, I: LogoutRequest, O: CommonResponse }
]);
