// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number
// @generated from protobuf file "exposed-donation.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { DonationService } from "./exposed-donation";
import type { GotDonationRequest } from "./exposed-donation";
import type { ClaimDonationRequest } from "./exposed-donation";
import type { GetDonationResponse } from "./exposed-donation";
import type { GetDonationRequest } from "./exposed-donation";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResponse } from "./exposed-common";
import type { UserDonationRequest } from "./exposed-donation";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service DonationService
 */
export interface IDonationServiceClient {
    /**
     * @generated from protobuf rpc: Donate
     */
    donate(input: UserDonationRequest, options?: RpcOptions): UnaryCall<UserDonationRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: GetMyDonations
     */
    getMyDonations(input: GetDonationRequest, options?: RpcOptions): UnaryCall<GetDonationRequest, GetDonationResponse>;
    /**
     * @generated from protobuf rpc: GetDonations
     */
    getDonations(input: GetDonationRequest, options?: RpcOptions): UnaryCall<GetDonationRequest, GetDonationResponse>;
    /**
     * @generated from protobuf rpc: ClaimDonation
     */
    claimDonation(input: ClaimDonationRequest, options?: RpcOptions): UnaryCall<ClaimDonationRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: GotDonation
     */
    gotDonation(input: GotDonationRequest, options?: RpcOptions): UnaryCall<GotDonationRequest, CommonResponse>;
}
/**
 * @generated from protobuf service DonationService
 */
export class DonationServiceClient implements IDonationServiceClient, ServiceInfo {
    typeName = DonationService.typeName;
    methods = DonationService.methods;
    options = DonationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Donate
     */
    donate(input: UserDonationRequest, options?: RpcOptions): UnaryCall<UserDonationRequest, CommonResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserDonationRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMyDonations
     */
    getMyDonations(input: GetDonationRequest, options?: RpcOptions): UnaryCall<GetDonationRequest, GetDonationResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDonationRequest, GetDonationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDonations
     */
    getDonations(input: GetDonationRequest, options?: RpcOptions): UnaryCall<GetDonationRequest, GetDonationResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDonationRequest, GetDonationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ClaimDonation
     */
    claimDonation(input: ClaimDonationRequest, options?: RpcOptions): UnaryCall<ClaimDonationRequest, CommonResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClaimDonationRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GotDonation
     */
    gotDonation(input: GotDonationRequest, options?: RpcOptions): UnaryCall<GotDonationRequest, CommonResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GotDonationRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
}
