// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number
// @generated from protobuf file "exposed-common.proto" (syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message EmptyRequest
 */
export interface EmptyRequest {
}
/**
 * @generated from protobuf message CommonResponse
 */
export interface CommonResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message Organization
 */
export interface Organization {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string address = 2
     */
    address: string;
    /**
     * @generated from protobuf field: float latitude = 3
     */
    latitude: number;
    /**
     * @generated from protobuf field: float longitude = 4
     */
    longitude: number;
    /**
     * @generated from protobuf field: string govtId = 5
     */
    govtId: string;
    /**
     * @generated from protobuf field: string contactNumber = 6
     */
    contactNumber: string;
}
/**
 * @generated from protobuf message User
 */
export interface User {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string createdAt = 2
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string firstName = 3
     */
    firstName: string;
    /**
     * @generated from protobuf field: string middleName = 4
     */
    middleName: string;
    /**
     * @generated from protobuf field: string lastName = 5
     */
    lastName: string;
    /**
     * @generated from protobuf field: float latitude = 6
     */
    latitude: number;
    /**
     * @generated from protobuf field: float longitude = 7
     */
    longitude: number;
}
/**
 * @generated from protobuf message Auth
 */
export interface Auth {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string createdAt = 2
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string email = 3
     */
    email: string;
    /**
     * @generated from protobuf field: string phone = 7
     */
    phone: string;
    /**
     * @generated from protobuf field: string isEmailVerified = 4
     */
    isEmailVerified: string;
    /**
     * @generated from protobuf field: Role role = 5
     */
    role: Role;
    /**
     * @generated from protobuf field: AuthStatus status = 6
     */
    status: AuthStatus;
}
/**
 * @generated from protobuf message AuthStatusHistory
 */
export interface AuthStatusHistory {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string createdAt = 2
     */
    createdAt: string;
    /**
     * @generated from protobuf field: AuthStatus status = 3
     */
    status: AuthStatus;
}
/**
 * @generated from protobuf message AuthDetail
 */
export interface AuthDetail {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string createdAt = 2
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string email = 3
     */
    email: string;
    /**
     * @generated from protobuf field: string phone = 4
     */
    phone: string;
    /**
     * @generated from protobuf field: string isEmailVerified = 5
     */
    isEmailVerified: string;
    /**
     * @generated from protobuf field: Role role = 6
     */
    role: Role;
    /**
     * @generated from protobuf field: AuthStatus status = 7
     */
    status: AuthStatus;
    /**
     * @generated from protobuf field: repeated AuthStatusHistory history = 8
     */
    history: AuthStatusHistory[];
    /**
     * @generated from protobuf field: string emailVerificationToken = 9
     */
    emailVerificationToken: string;
    /**
     * @generated from protobuf field: string emailVerificationPublishAt = 10
     */
    emailVerificationPublishAt: string;
}
/**
 * @generated from protobuf message Pagination
 */
export interface Pagination {
    /**
     * @generated from protobuf field: int32 page = 1
     */
    page: number;
    /**
     * @generated from protobuf field: int32 size = 2
     */
    size: number;
    /**
     * @generated from protobuf field: int32 total = 3
     */
    total: number;
    /**
     * @generated from protobuf field: int32 totalPages = 4
     */
    totalPages: number;
}
/**
 * @generated from protobuf enum Role
 */
export enum Role {
    /**
     * @generated from protobuf enum value: ROLE_UNSPECIFIED = 0;
     */
    ROLE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: SUDO_ADMIN = 1;
     */
    SUDO_ADMIN = 1,
    /**
     * @generated from protobuf enum value: ADMIN = 2;
     */
    ADMIN = 2,
    /**
     * @generated from protobuf enum value: USER = 3;
     */
    USER = 3,
    /**
     * @generated from protobuf enum value: ORGANIZATION_SUPER_ADMIN = 4;
     */
    ORGANIZATION_SUPER_ADMIN = 4,
    /**
     * @generated from protobuf enum value: ORGANIZATION_ADMIN = 5;
     */
    ORGANIZATION_ADMIN = 5
}
/**
 * @generated from protobuf enum AuthStatus
 */
export enum AuthStatus {
    /**
     * @generated from protobuf enum value: STATUS_UNSPECIFIED = 0;
     */
    STATUS_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: ACTIVE = 1;
     */
    ACTIVE = 1,
    /**
     * @generated from protobuf enum value: INACTIVE = 2;
     */
    INACTIVE = 2,
    /**
     * @generated from protobuf enum value: SUSPENDED = 3;
     */
    SUSPENDED = 3,
    /**
     * @generated from protobuf enum value: DELETED = 4;
     */
    DELETED = 4
}
/**
 * @generated from protobuf enum DonationType
 */
export enum DonationType {
    /**
     * @generated from protobuf enum value: DONATION_UNSPECIFIED = 0;
     */
    DONATION_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: BOOKS = 1;
     */
    BOOKS = 1,
    /**
     * @generated from protobuf enum value: CLOTHES = 2;
     */
    CLOTHES = 2
}
/**
 * @generated from protobuf enum DonationStatus
 */
export enum DonationStatus {
    /**
     * @generated from protobuf enum value: DONATION_STATUS_UNSPECIFIED = 0;
     */
    DONATION_STATUS_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: AVAILABLE = 1;
     */
    AVAILABLE = 1,
    /**
     * @generated from protobuf enum value: CLAIMED = 2;
     */
    CLAIMED = 2,
    /**
     * @generated from protobuf enum value: DONATED = 3;
     */
    DONATED = 3,
    /**
     * @generated from protobuf enum value: CANCELLED = 4;
     */
    CANCELLED = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class EmptyRequest$Type extends MessageType<EmptyRequest> {
    constructor() {
        super("EmptyRequest", []);
    }
    create(value?: PartialMessage<EmptyRequest>): EmptyRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<EmptyRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EmptyRequest): EmptyRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EmptyRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message EmptyRequest
 */
export const EmptyRequest = new EmptyRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CommonResponse$Type extends MessageType<CommonResponse> {
    constructor() {
        super("CommonResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CommonResponse>): CommonResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<CommonResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CommonResponse): CommonResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CommonResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message CommonResponse
 */
export const CommonResponse = new CommonResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Organization$Type extends MessageType<Organization> {
    constructor() {
        super("Organization", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "latitude", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 4, name: "longitude", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 5, name: "govtId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "contactNumber", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Organization>): Organization {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.address = "";
        message.latitude = 0;
        message.longitude = 0;
        message.govtId = "";
        message.contactNumber = "";
        if (value !== undefined)
            reflectionMergePartial<Organization>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Organization): Organization {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string address */ 2:
                    message.address = reader.string();
                    break;
                case /* float latitude */ 3:
                    message.latitude = reader.float();
                    break;
                case /* float longitude */ 4:
                    message.longitude = reader.float();
                    break;
                case /* string govtId */ 5:
                    message.govtId = reader.string();
                    break;
                case /* string contactNumber */ 6:
                    message.contactNumber = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Organization, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string address = 2; */
        if (message.address !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.address);
        /* float latitude = 3; */
        if (message.latitude !== 0)
            writer.tag(3, WireType.Bit32).float(message.latitude);
        /* float longitude = 4; */
        if (message.longitude !== 0)
            writer.tag(4, WireType.Bit32).float(message.longitude);
        /* string govtId = 5; */
        if (message.govtId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.govtId);
        /* string contactNumber = 6; */
        if (message.contactNumber !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.contactNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Organization
 */
export const Organization = new Organization$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User$Type extends MessageType<User> {
    constructor() {
        super("User", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "createdAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "firstName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "middleName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "lastName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "latitude", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 7, name: "longitude", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<User>): User {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.createdAt = "";
        message.firstName = "";
        message.middleName = "";
        message.lastName = "";
        message.latitude = 0;
        message.longitude = 0;
        if (value !== undefined)
            reflectionMergePartial<User>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User): User {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string createdAt */ 2:
                    message.createdAt = reader.string();
                    break;
                case /* string firstName */ 3:
                    message.firstName = reader.string();
                    break;
                case /* string middleName */ 4:
                    message.middleName = reader.string();
                    break;
                case /* string lastName */ 5:
                    message.lastName = reader.string();
                    break;
                case /* float latitude */ 6:
                    message.latitude = reader.float();
                    break;
                case /* float longitude */ 7:
                    message.longitude = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string createdAt = 2; */
        if (message.createdAt !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.createdAt);
        /* string firstName = 3; */
        if (message.firstName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.firstName);
        /* string middleName = 4; */
        if (message.middleName !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.middleName);
        /* string lastName = 5; */
        if (message.lastName !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.lastName);
        /* float latitude = 6; */
        if (message.latitude !== 0)
            writer.tag(6, WireType.Bit32).float(message.latitude);
        /* float longitude = 7; */
        if (message.longitude !== 0)
            writer.tag(7, WireType.Bit32).float(message.longitude);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message User
 */
export const User = new User$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Auth$Type extends MessageType<Auth> {
    constructor() {
        super("Auth", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "createdAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "isEmailVerified", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "role", kind: "enum", T: () => ["Role", Role] },
            { no: 6, name: "status", kind: "enum", T: () => ["AuthStatus", AuthStatus] }
        ]);
    }
    create(value?: PartialMessage<Auth>): Auth {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.createdAt = "";
        message.email = "";
        message.phone = "";
        message.isEmailVerified = "";
        message.role = 0;
        message.status = 0;
        if (value !== undefined)
            reflectionMergePartial<Auth>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Auth): Auth {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string createdAt */ 2:
                    message.createdAt = reader.string();
                    break;
                case /* string email */ 3:
                    message.email = reader.string();
                    break;
                case /* string phone */ 7:
                    message.phone = reader.string();
                    break;
                case /* string isEmailVerified */ 4:
                    message.isEmailVerified = reader.string();
                    break;
                case /* Role role */ 5:
                    message.role = reader.int32();
                    break;
                case /* AuthStatus status */ 6:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Auth, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string createdAt = 2; */
        if (message.createdAt !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.createdAt);
        /* string email = 3; */
        if (message.email !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.email);
        /* string isEmailVerified = 4; */
        if (message.isEmailVerified !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.isEmailVerified);
        /* Role role = 5; */
        if (message.role !== 0)
            writer.tag(5, WireType.Varint).int32(message.role);
        /* AuthStatus status = 6; */
        if (message.status !== 0)
            writer.tag(6, WireType.Varint).int32(message.status);
        /* string phone = 7; */
        if (message.phone !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.phone);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Auth
 */
export const Auth = new Auth$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AuthStatusHistory$Type extends MessageType<AuthStatusHistory> {
    constructor() {
        super("AuthStatusHistory", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "createdAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "status", kind: "enum", T: () => ["AuthStatus", AuthStatus] }
        ]);
    }
    create(value?: PartialMessage<AuthStatusHistory>): AuthStatusHistory {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.createdAt = "";
        message.status = 0;
        if (value !== undefined)
            reflectionMergePartial<AuthStatusHistory>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AuthStatusHistory): AuthStatusHistory {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string createdAt */ 2:
                    message.createdAt = reader.string();
                    break;
                case /* AuthStatus status */ 3:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AuthStatusHistory, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string createdAt = 2; */
        if (message.createdAt !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.createdAt);
        /* AuthStatus status = 3; */
        if (message.status !== 0)
            writer.tag(3, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message AuthStatusHistory
 */
export const AuthStatusHistory = new AuthStatusHistory$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AuthDetail$Type extends MessageType<AuthDetail> {
    constructor() {
        super("AuthDetail", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "createdAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "isEmailVerified", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "role", kind: "enum", T: () => ["Role", Role] },
            { no: 7, name: "status", kind: "enum", T: () => ["AuthStatus", AuthStatus] },
            { no: 8, name: "history", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => AuthStatusHistory },
            { no: 9, name: "emailVerificationToken", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "emailVerificationPublishAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AuthDetail>): AuthDetail {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.createdAt = "";
        message.email = "";
        message.phone = "";
        message.isEmailVerified = "";
        message.role = 0;
        message.status = 0;
        message.history = [];
        message.emailVerificationToken = "";
        message.emailVerificationPublishAt = "";
        if (value !== undefined)
            reflectionMergePartial<AuthDetail>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AuthDetail): AuthDetail {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string createdAt */ 2:
                    message.createdAt = reader.string();
                    break;
                case /* string email */ 3:
                    message.email = reader.string();
                    break;
                case /* string phone */ 4:
                    message.phone = reader.string();
                    break;
                case /* string isEmailVerified */ 5:
                    message.isEmailVerified = reader.string();
                    break;
                case /* Role role */ 6:
                    message.role = reader.int32();
                    break;
                case /* AuthStatus status */ 7:
                    message.status = reader.int32();
                    break;
                case /* repeated AuthStatusHistory history */ 8:
                    message.history.push(AuthStatusHistory.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string emailVerificationToken */ 9:
                    message.emailVerificationToken = reader.string();
                    break;
                case /* string emailVerificationPublishAt */ 10:
                    message.emailVerificationPublishAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AuthDetail, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string createdAt = 2; */
        if (message.createdAt !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.createdAt);
        /* string email = 3; */
        if (message.email !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.email);
        /* string phone = 4; */
        if (message.phone !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.phone);
        /* string isEmailVerified = 5; */
        if (message.isEmailVerified !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.isEmailVerified);
        /* Role role = 6; */
        if (message.role !== 0)
            writer.tag(6, WireType.Varint).int32(message.role);
        /* AuthStatus status = 7; */
        if (message.status !== 0)
            writer.tag(7, WireType.Varint).int32(message.status);
        /* repeated AuthStatusHistory history = 8; */
        for (let i = 0; i < message.history.length; i++)
            AuthStatusHistory.internalBinaryWrite(message.history[i], writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* string emailVerificationToken = 9; */
        if (message.emailVerificationToken !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.emailVerificationToken);
        /* string emailVerificationPublishAt = 10; */
        if (message.emailVerificationPublishAt !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.emailVerificationPublishAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message AuthDetail
 */
export const AuthDetail = new AuthDetail$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Pagination$Type extends MessageType<Pagination> {
    constructor() {
        super("Pagination", [
            { no: 1, name: "page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "size", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "total", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "totalPages", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Pagination>): Pagination {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.page = 0;
        message.size = 0;
        message.total = 0;
        message.totalPages = 0;
        if (value !== undefined)
            reflectionMergePartial<Pagination>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Pagination): Pagination {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 page */ 1:
                    message.page = reader.int32();
                    break;
                case /* int32 size */ 2:
                    message.size = reader.int32();
                    break;
                case /* int32 total */ 3:
                    message.total = reader.int32();
                    break;
                case /* int32 totalPages */ 4:
                    message.totalPages = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Pagination, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 page = 1; */
        if (message.page !== 0)
            writer.tag(1, WireType.Varint).int32(message.page);
        /* int32 size = 2; */
        if (message.size !== 0)
            writer.tag(2, WireType.Varint).int32(message.size);
        /* int32 total = 3; */
        if (message.total !== 0)
            writer.tag(3, WireType.Varint).int32(message.total);
        /* int32 totalPages = 4; */
        if (message.totalPages !== 0)
            writer.tag(4, WireType.Varint).int32(message.totalPages);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Pagination
 */
export const Pagination = new Pagination$Type();
