// @generated by protobuf-ts 2.11.1 with parameter optimize_code_size,long_type_number
// @generated from protobuf file "exposed-auth.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthService } from "./exposed-auth";
import type { VerifyEmailRequest } from "./exposed-auth";
import type { LogoutRequest } from "./exposed-auth";
import type { MyInfoResponse } from "./exposed-auth";
import type { EmptyRequest } from "./exposed-common";
import type { UpdateAuthStatusRequest } from "./exposed-auth";
import type { RegisterAdminRequest } from "./exposed-auth";
import type { RegisterOrganizationRequest } from "./exposed-auth";
import type { CommonResponse } from "./exposed-common";
import type { RegisterUserRequest } from "./exposed-auth";
import type { RefreshTokenResponse } from "./exposed-auth";
import type { RefreshTokenRequest } from "./exposed-auth";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { LoginResponse } from "./exposed-auth";
import type { LoginRequest } from "./exposed-auth";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service AuthService
 */
export interface IAuthServiceClient {
    /**
     * @generated from protobuf rpc: Login
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse>;
    /**
     * @generated from protobuf rpc: RefreshToken
     */
    refreshToken(input: RefreshTokenRequest, options?: RpcOptions): UnaryCall<RefreshTokenRequest, RefreshTokenResponse>;
    /**
     * @generated from protobuf rpc: RegisterUser
     */
    registerUser(input: RegisterUserRequest, options?: RpcOptions): UnaryCall<RegisterUserRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: RegisterOrganization
     */
    registerOrganization(input: RegisterOrganizationRequest, options?: RpcOptions): UnaryCall<RegisterOrganizationRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: RegisterAdmin
     */
    registerAdmin(input: RegisterAdminRequest, options?: RpcOptions): UnaryCall<RegisterAdminRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: UpdateAuthStatus
     */
    updateAuthStatus(input: UpdateAuthStatusRequest, options?: RpcOptions): UnaryCall<UpdateAuthStatusRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: MyInfo
     */
    myInfo(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, MyInfoResponse>;
    /**
     * @generated from protobuf rpc: Logout
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: VerifyEmail
     */
    verifyEmail(input: VerifyEmailRequest, options?: RpcOptions): UnaryCall<VerifyEmailRequest, CommonResponse>;
}
/**
 * @generated from protobuf service AuthService
 */
export class AuthServiceClient implements IAuthServiceClient, ServiceInfo {
    typeName = AuthService.typeName;
    methods = AuthService.methods;
    options = AuthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Login
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, LoginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RefreshToken
     */
    refreshToken(input: RefreshTokenRequest, options?: RpcOptions): UnaryCall<RefreshTokenRequest, RefreshTokenResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<RefreshTokenRequest, RefreshTokenResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RegisterUser
     */
    registerUser(input: RegisterUserRequest, options?: RpcOptions): UnaryCall<RegisterUserRequest, CommonResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterUserRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RegisterOrganization
     */
    registerOrganization(input: RegisterOrganizationRequest, options?: RpcOptions): UnaryCall<RegisterOrganizationRequest, CommonResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterOrganizationRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RegisterAdmin
     */
    registerAdmin(input: RegisterAdminRequest, options?: RpcOptions): UnaryCall<RegisterAdminRequest, CommonResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterAdminRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateAuthStatus
     */
    updateAuthStatus(input: UpdateAuthStatusRequest, options?: RpcOptions): UnaryCall<UpdateAuthStatusRequest, CommonResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateAuthStatusRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: MyInfo
     */
    myInfo(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, MyInfoResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmptyRequest, MyInfoResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Logout
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, CommonResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: VerifyEmail
     */
    verifyEmail(input: VerifyEmailRequest, options?: RpcOptions): UnaryCall<VerifyEmailRequest, CommonResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<VerifyEmailRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
}
