syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.charitable.app.proto";
option java_outer_classname = "AuthProto";

import "exposed-common.proto";

service AuthService {
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
  rpc RegisterUser (RegisterUserRequest) returns (CommonResponse);
  rpc RegisterOrganization (RegisterOrganizationRequest) returns (CommonResponse);
  rpc RegisterAdmin(RegisterAdminRequest) returns (CommonResponse);

  rpc UpdateAuthStatus(UpdateAuthStatusRequest) returns (CommonResponse);

  rpc MyInfo(EmptyRequest) returns (MyInfoResponse);
  rpc Logout (LogoutRequest) returns (CommonResponse);

  rpc VerifyEmail(VerifyEmailRequest) returns (CommonResponse);
}

message RegisterAdminRequest {
  string email = 1;
  string password = 2;
  string phone_number = 3;

  string firstName = 4;
  string middleName = 5;
  string lastName = 6;
}

message LoginRequest {
  string username = 1;
  string password = 2;
}

message AuthTokenResponse {
  string accessToken = 1;
  string refreshToken =2;
}

message LoginResponse {
  bool success = 1;
  string message = 2;
  AuthTokenResponse data =3;
}

message RefreshTokenRequest {
  string refreshToken = 1;
}

message RefreshTokenResponse {
  bool success = 1;
  string message = 2;
  AuthTokenResponse data =3;
}


message RegisterUserRequest {
  string email = 1;
  string password = 2;
  string phone_number = 3;

  string firstName = 4;
  string middleName = 5;
  string lastName = 6;
  float latitude = 7;
  float longitude = 8;
}

message RegisterOrganizationRequest {
  string email = 4;
  string password = 3;
  string phone_number = 2;

  string organization_name = 1;

  string organizationHeadFirstName = 10;
  string organizationHeadMiddleName = 11;
  string organizationHeadLastName = 12;
  string organizationHeadPhoneNumber = 13;

  string address = 5;
  float latitude = 6;
  float longitude = 7;
  string govt_id = 8;
  string contact_number = 9;
}


message LogoutRequest {}

message UpdateAuthStatusRequest {
  string auth_id = 1;
  AuthStatus status = 2;
}

message MyInfoData {
  string id = 1;
  string createdAt = 2;
  string email = 3;
  string phone = 4;
  Role role = 5;
  AuthStatus status = 6;
  Organization organization = 7;
  User user = 8;
}

message MyInfoResponse {
  bool success = 1;
  string message = 2;
  MyInfoData data = 3;
}

message VerifyEmailRequest {
  string token = 1;
}